---
- hosts: localhost
  become: yes

  vars:
   remote_dir: "/etc/ansible/facts.d"
   facts_file: example1.fact

  tasks:
   - name: create custom directory
     file:
      state: directory
      recurse: yes
      path: "{{ remote_dir }}"

   - name: copy the custom fact
     copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"
